# Generated by Django 2.2 on 2021-06-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='id',
            options={},
        ),
    ]
